opt_in_rules:
- file_header

disabled_rules:
- cyclomatic_complexity

included:
- Sources
- Tests

excluded:
- Sources/SundayServer/Routable.swift

opt_in_rules:
- file_header

vertical_whitespace:
  max_empty_lines: 3

nesting:
  type_level: 2

statement_position:
  statement_mode: uncuddled_else

identifier_name:
  excluded: [id, ok, in, is, at, of]

trailing_comma:
  mandatory_comma: true

file_length:
  warning: 800
  error: 1000
  ignore_comment_only_lines: true

line_length:
  - 150
  - 175

function_body_length:
  - 300
  - 350  

type_body_length:
  - 400
  - 450

large_tuple:
  - 4
  - 5

file_header:
  required_pattern: |-
    \Q/*
     * MIT License
     *
     * Copyright \E\d{4}\Q Outfox, inc.
     *
     * Permission is hereby granted, free of charge, to any person obtaining a copy
     * of this software and associated documentation files (the "Software"), to deal
     * in the Software without restriction, including without limitation the rights
     * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
     * copies of the Software, and to permit persons to whom the Software is
     * furnished to do so, subject to the following conditions:
     *
     * The above copyright notice and this permission notice shall be included in all
     * copies or substantial portions of the Software.
     *
     * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
     * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
     * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
     * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
     * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
     * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
     * SOFTWARE.
     */\E
