opt_in_rules:
- file_header

disabled_rules:
- cyclomatic_complexity

included:
- Sources
- Tests

excluded:
- Sources/SundayServer/Routable.swift

vertical_whitespace:
  max_empty_lines: 3

nesting:
  type_level: 2

statement_position:
  statement_mode: uncuddled_else

identifier_name:
  excluded: [id, ok, in, is, at, of]

trailing_comma:
  mandatory_comma: true

file_length:
  warning: 1500
  error: 3000
  ignore_comment_only_lines: true

line_length:
  - 150
  - 175

function_parameter_count:
- 8
- 11

function_body_length:
  - 300
  - 350  

type_body_length:
  - 700
  - 1000

large_tuple:
  - 4
  - 5

file_header:
  required_pattern: |-
    \Q//
    //  \E[a-zA-Z0-9-_.]+\Q
    //  PotentCodables
    //
    //  Copyright © \E\d{4}\Q Outfox, inc.
    //
    //
    //  Distributed under the MIT License, See LICENSE for details.
    //
    \E
