name: PotentCodablesTest
packages:
  PotentCodables:
    url: https://github.com/outfoxx/PotentCodables.git
    from: 0.0.0
localPackages:
  - ../PotentCodables
options:
  bundleIdPrefix: io.outfoxx
targets:
  PotentCodablesWrap:
    type: framework.static
    platform: [macOS, iOS, tvOS, watchOS]
    deploymentTarget:
      macOS: 10.12
      iOS: 10.0
      tvOS: 10.0
      watchOS: 3.0
    sources: []
    info:
      path: Project/${platform}/Info.plist
    scheme:
      testTargets:
        - PotentCodablesTests_${platform}
    dependencies:
      - package: PotentCodables
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.outfoxx.PotentCodablesWrap

  PotentCodablesTests:
    type: bundle.unit-test
    platform: [macOS, iOS, tvOS, watchOS]
    deploymentTarget:
      iOS: 10.0
      tvOS: 10.0
      watchOS: 3.0
    sources: [Tests]
    dependencies:
      - target: PotentCodablesWrap_${platform}
        link: true
    settings:
      GENERATE_INFOPLIST_FILE: true
